#!/bin/sh

. "$(dirname "$0")/_/husky.sh"


echo '*** Linting, Formatting and Testing before committing ***'


npx tsc || (
    echo -e '\033[0;31m❌❌❌ Failed Type check. ❌❌❌\033[0m'
    false)

npx lint-staged  || (
    echo '❌❌❌ Failed lint-staged check. ❌❌❌'
    false;
)


echo '🏹🏹 Linting, Styling and Testing passed... This changes will be committed now. 🏹🏹'